name: social_media_automation
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # পুরনো প্যাকেজটি সরিয়ে নতুন এবং আপডেটেড প্যাকেজটি যুক্ত করা হলো
  flutter_facebook_auth: ^7.1.1 
  
  http: ^1.6.0
  shared_preferences: ^2.5.3
  get: ^4.7.3
  url_launcher: ^6.3.2
  image_picker: ^1.2.1
  supabase_flutter: ^2.15.4
  google_sign_in: ^6.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true