name: social_media_automation
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_facebook_auth: ^7.1.1 
  http: ^1.6.0
  shared_preferences: ^2.5.3
  get: ^4.7.3
  url_launcher: ^6.3.2
  image_picker: ^1.2.1
  supabase_flutter: ^2.15.4
  google_sign_in: ^6.2.1
  gal: ^2.3.3
  flutter_colorpicker: ^1.1.0
  path_provider: ^2.1.5
  flutter_dotenv: ^5.1.0 # 👈 ১. প্যাকেজটি যুক্ত করা হয়েছে
  google_generative_ai: ^0.4.0 # Gemini AI চ্যাট হ্যান্ডেল করার জন্য
  package_info_plus: ^8.0.0    # অ্যাপ ভার্সন পাওয়ার জন্য

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # 🖼️ Local Assets Path
  assets:
    - assets/images/
    - .env # 👈 ২. এখানে .env ফাইল যুক্ত করা হলো